# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed67be3b3901f23de8ac41de4dad18c16b998a01561df0bd7c6ecb7b63e88cef0c1fa255cc63efd51dc4f594d74e5d483521528103e741ac29c7a2b16348c6ad

test:
  secret_key_base: 82710c908e580f660172fec49c364e936b731534b5f84475d75823a87d219b3e70ac8f756597cca99eb1faf743d6855751621c1c7445253384e2834a9706a34a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
